### ISSUE TITLE
getting a "redefinition of constant Node" while running train_aleph.ipynb

### ISSUE THREAD

**Issue by samamiller** [imagry/aleph_star#1]
LoadError: invalid redefinition of constant Node in expression starting at ..\data_structures.jl:2

**Comment by skariel** [comment]
hi, I cannot reproduce. I just cloned this repository, and using Julia v1, in the root folder of this repository I run `include("aleph_star/aleph_star.jl")` and it succeeds, the definition of `Node` is included in there.

can you describe the exact steps that lead to this error?

**Comment by skariel** [comment]
ahhh I see your problem. The error is `redefinition`. It happens when you include the file twice. You should run the include command only once, but even with the error, you can continue to the training, the error just tells you that the struct `Node` is already defined and cannot be defined again, but once is enough. Just ignore the error. 

This is not a bug, just the way Julia works.
